#siplo_lms:
#    resource: "@SiploLMSBundle/Controller/DefaultController.php"
#    type:     annotation
#    prefix:   /

siplo_user:
    resource: "@SiploUserBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

student_registration:
    pattern:  /register/student
    defaults: { _controller: SiploUserBundle:Registration:registerStudent }

teacher_registration:
    pattern:  /register/teacher
    defaults: { _controller: SiploUserBundle:Registration:registerTeacher }

guardian_registration:
    pattern:  /register/guardian
    defaults: { _controller: SiploUserBundle:Registration:registerGuardian }

admin_registration:
    pattern:  /register/admin
    defaults: { _controller: SiploUserBundle:Registration:registerAdmin }

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
