siplo_lms:
    resource: "@SiploLMSBundle/Controller/DefaultController.php"
    type:     annotation
    prefix:   /

#siplo_user:
#    resource: "@SiploUserBundle/Controller/"
#    type:     annotation
#    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

student_registration:
    pattern:  /register/student
    defaults: { _controller: SiploUserBundle:StudentRegistration:register }

teacher_registration:
    pattern:  /register/teacher
    defaults: { _controller: SiploUserBundle:TeacherRegistration:register }

guardian_registration:
    pattern:  /register/guardian
    defaults: { _controller: SiploUserBundle:GuardianRegistration:register }

admin_registration:
    pattern:  /register/admin
    defaults: { _controller: SiploUserBundle:AdminRegistration:register }

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
