# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
#parameters:
#    parameter_name: value

#services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

parameters:
    siplo_user_security.login_success_handler.class: Siplo\UserBundle\Services\LoginSuccessHandler
#    ccdn_user_security.component.authentication.handler.logout_success_handler.class: CCDNUser\SecurityBundle\Component\Authentication\Handler\LogoutSuccessHandler

services:
    siplo_login_success_handler:
        class:  Siplo\UserBundle\Services\LoginSuccessHandler
        arguments:  [@router, @security.context]
        tags:
            - { name: 'monolog.logger', channel: 'security' }


#    ccdn_user_security.component.authentication.handler.logout_success_handler:
#        class:  %ccdn_user_security.component.authentication.handler.logout_success_handler.class%
#        arguments:  [@service_container, @router]
#        tags:
#            - { name: 'monolog.logger', channel: 'security' }